### ISSUE TITLE
error

### ISSUE THREAD

**Issue by annu02909** [37sy/build_aab_tool#3]
[base]-Compressed zip
Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 10: illegal multibyte sequence

**Comment by 37sy** [comment]
Recovered。
